import React,{useEffect,useState,useRef,useCallback} from 'react';
import App from '../App.jsx';
import {PreviewViewport} from './PreviewViewport.jsx';
import {basePath,getLocale} from '../locale.js';
import {ContentSnapshotProvider} from './snapshot-context.jsx';
import {validateSnapshot} from './snapshot.js';
function notifyParent(revisionId,state){if(window.parent===window)return;const configured=import.meta.env.DEV?import.meta.env.VITE_CONTENT_ADMIN_ORIGIN:undefined;const target=configured&&/^http:\/\/(localhost|127\.0\.0\.1):\d+$/.test(configured)?configured:'https://www.stardotsglobal.com';window.parent.postMessage({type:'cms-preview',siteId:'bags',revisionId,state},target);}
export function DraftPreview(){const [data,setData]=useState(null),[error,setError]=useState(''),[width,setWidth]=useState(1440),[lang,setLang]=useState('zh'),[view,setView]=useState(null);const previewRequest=useRef(null),expectedRevision=useRef('');const notifyReady=useCallback(()=>{if(data&&!error)notifyParent(data.revision.id,'ready');},[data,error]);useEffect(()=>{if(error)notifyParent(expectedRevision.current,'error');},[error]);
 useEffect(()=>{let alive=true;if(!previewRequest.current){const ticket=new URLSearchParams(window.location.hash.slice(1)).get('ticket');expectedRevision.current=new URLSearchParams(window.location.hash.slice(1)).get('revision')??'';window.history.replaceState(null,'',window.location.pathname);if(!ticket){setError('没有有效预览链接，请在后台重新预览。');return;}
  previewRequest.current=fetch('/api/content-preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ticket})}).then(async r=>{if(!r.ok)throw Error('preview');return r.json();});}previewRequest.current.then(result=>{validateSnapshot(result.snapshot);if(alive)setData(result);}).catch(()=>{if(alive)setError('预览不可用或已过期，请在后台重新预览。');});return()=>{alive=false;};},[]);
 useEffect(()=>{if(!data)return;const timer=setTimeout(()=>{notifyParent(data.revision.id,'expired');setData(null);setError('预览已到期，请在后台重新预览。');},Math.max(0,Date.parse(data.expiresAt)-Date.now()));return()=>clearTimeout(timer);},[data]);
 useEffect(()=>{window.history.replaceState(null,'',lang==='zh'?'/zh/content-preview':'/content-preview');document.documentElement.lang=lang==='zh'?'zh-CN':'en';},[lang]);
 function chooseLang(next){window.history.replaceState(null,'',next==='zh'?'/zh/content-preview':'/content-preview');document.documentElement.lang=next==='zh'?'zh-CN':'en';setLang(next);}
 if(error)return <main className="container" style={{padding:32}}><h1>草稿预览</h1><p role="alert">{error}</p></main>;if(!data)return <main className="container" style={{padding:32}} role="status">正在验证草稿预览…</main>;
 const path=view??(data.revision.kind==='product'?`/products/models/${data.revision.content.slug}`:data.revision.content.slot.startsWith('about-')?'/about':'/');
 return <><div style={{padding:16,background:'#0b253d',color:'white',display:'flex',flexWrap:'wrap',gap:16,alignItems:'center'}}><strong>草稿预览 · 尚未发布</strong><span>10 分钟内有效</span><button onClick={()=>chooseLang(lang==='zh'?'en':'zh')}>{lang==='zh'?'English':'中文'}</button><label>显示宽度<select value={width} onChange={e=>setWidth(Number(e.target.value))}><option value={375}>手机 375px</option><option value={1440}>桌面 1440px</option></select></label></div><div style={{overflowX:'auto'}}><PreviewViewport width={width} lang={lang} onReady={notifyReady}><div onSubmitCapture={e=>{e.preventDefault();e.stopPropagation();}} onClickCapture={e=>{const a=e.target.closest?.('a[href]');if(!a)return;const url=new URL(a.href);if(url.origin===window.location.origin){e.preventDefault();const p=basePath(url.pathname);if(p!=='/content-preview')setView(p);chooseLang(getLocale(url.pathname));}}}><ContentSnapshotProvider snapshot={data.snapshot} assetUrls={data.assetUrls}><App previewPath={path}/></ContentSnapshotProvider></div></PreviewViewport></div></>;
}
